2025-03-15 15:35:44,753 - root - ‚ÑπÔ∏è INFO - main.py:69 - Initializing pipeline
2025-03-15 15:35:44,754 - root - ‚ÑπÔ∏è INFO - main.py:13 - Starting Twitter scraper for @LBCI_NEWS
2025-03-15 15:35:49,963 - root - ‚ÑπÔ∏è INFO - core.py:25 - üöÄ Starting scrape for @LBCI_NEWS
2025-03-15 15:35:57,055 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 5 new tweets (Total: 5)
2025-03-15 15:35:58,287 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 2 new tweets (Total: 7)
2025-03-15 15:35:59,564 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 2 new tweets (Total: 9)
2025-03-15 15:36:00,739 - root - ‚ÑπÔ∏è INFO - producer.py:22 - Sent batch of 10 tweets (Total: 10)
2025-03-15 15:36:00,742 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 2 new tweets (Total: 11)
2025-03-15 15:36:02,153 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 14)
2025-03-15 15:36:03,392 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 5 new tweets (Total: 19)
2025-03-15 15:36:04,452 - root - ‚ÑπÔ∏è INFO - producer.py:22 - Sent batch of 10 tweets (Total: 20)
2025-03-15 15:36:04,452 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 1 new tweets (Total: 20)
2025-03-15 15:36:06,138 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 5 new tweets (Total: 25)
2025-03-15 15:36:07,478 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 2 new tweets (Total: 27)
2025-03-15 15:36:09,338 - root - ‚ÑπÔ∏è INFO - producer.py:22 - Sent batch of 10 tweets (Total: 30)
2025-03-15 15:36:09,340 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 4 new tweets (Total: 31)
2025-03-15 15:36:10,452 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 2 new tweets (Total: 33)
2025-03-15 15:36:11,596 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 36)
2025-03-15 15:36:12,737 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 39)
2025-03-15 15:36:13,655 - root - ‚ö†Ô∏è WARNING - core.py:77 - ‚ö†Ô∏è  No new tweets in loaded content
2025-03-15 15:36:13,656 - root - ‚ö†Ô∏è WARNING - core.py:82 - ‚è≥ Retry #1 for 2s
2025-03-15 15:36:16,681 - root - ‚ÑπÔ∏è INFO - producer.py:22 - Sent batch of 10 tweets (Total: 40)
2025-03-15 15:36:16,687 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 5 new tweets (Total: 44)
2025-03-15 15:36:17,493 - root - ‚ö†Ô∏è WARNING - core.py:77 - ‚ö†Ô∏è  No new tweets in loaded content
2025-03-15 15:36:17,493 - root - ‚ö†Ô∏è WARNING - core.py:82 - ‚è≥ Retry #1 for 2s
2025-03-15 15:36:20,272 - root - ‚ö†Ô∏è WARNING - core.py:77 - ‚ö†Ô∏è  No new tweets in loaded content
2025-03-15 15:36:20,272 - root - ‚ö†Ô∏è WARNING - core.py:82 - ‚è≥ Retry #2 for 4s
2025-03-15 15:36:25,357 - root - ‚ÑπÔ∏è INFO - producer.py:22 - Sent batch of 10 tweets (Total: 50)
2025-03-15 15:36:25,358 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 6 new tweets (Total: 50)
2025-03-15 15:36:27,434 - root - ‚ÑπÔ∏è INFO - core.py:93 - ‚úÖ Final count: 50/50 tweets
2025-03-15 15:36:27,434 - root - ‚ÑπÔ∏è INFO - core.py:95 - üéØ Target reached successfully
2025-03-15 15:36:27,434 - root - ‚ÑπÔ∏è INFO - main.py:21 - Scraping completed for @LBCI_NEWS
2025-03-15 15:36:27,434 - root - ‚ÑπÔ∏è INFO - producer.py:29 - Final count: 50 tweets sent
2025-03-15 15:36:27,437 - root - ‚ÑπÔ∏è INFO - main.py:28 - Starting storage consumer
2025-03-15 15:36:27,441 - root - ‚ÑπÔ∏è INFO - main.py:40 - Starting stats consumers
2025-03-15 15:36:30,552 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,557 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,563 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,566 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,571 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,575 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,580 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,584 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,589 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,594 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,598 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,603 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,608 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,611 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,616 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,619 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,623 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,628 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,632 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,636 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,639 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,642 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,646 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,651 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,654 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,657 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,662 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,665 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,668 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,672 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,677 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,679 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,683 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,685 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,690 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,692 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,697 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,699 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,702 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,705 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,708 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,711 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,716 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,719 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,722 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,726 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,731 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,734 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,739 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,742 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,747 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,750 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,755 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,758 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,762 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,765 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,770 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,773 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,777 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,781 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,785 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,788 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,791 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,795 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,799 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,802 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,808 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,811 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,816 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,820 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,824 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,828 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,832 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,834 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,840 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,843 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,847 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,850 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,854 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,857 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,861 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,863 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,868 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,871 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,875 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,878 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,883 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,886 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,891 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,894 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,898 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,901 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,905 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,909 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,912 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,916 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,919 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,923 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:30,926 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:36:30,929 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:36:41,027 - root - ‚ÑπÔ∏è INFO - main.py:33 - Storage consumer finished
2025-03-15 15:37:00,797 - src.kafka.consumers.stats - ‚ÑπÔ∏è INFO - stats.py:48 - Top 20 word frequencies saved to C:\Users\Admin\PycharmProjects\SocialMediaPipeline\data\word_frequencies.json
2025-03-15 15:37:00,798 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:157 - Word frequencies inserted successfully.
2025-03-15 15:37:00,798 - src.kafka.consumers.stats - ‚ÑπÔ∏è INFO - stats.py:52 - Word frequencies saved to database
2025-03-15 15:37:34,190 - src.kafka.consumers.stats - ‚ÑπÔ∏è INFO - stats.py:90 - Engagement metrics saved to C:\Users\Admin\PycharmProjects\SocialMediaPipeline\data\tweets_engagement.json
2025-03-15 15:37:34,198 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ÿßÿ≥ÿ™ŸáÿØÿßŸÅ ÿ≥Ÿäÿßÿ±ÿ© ŸÅŸä ÿ®ÿ±ÿ¨ ÿßŸÑŸÖŸÑŸàŸÉ...' with post_date 2025-03-15 and post_time 11:43:27
2025-03-15 15:37:34,201 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ÿßŸÑÿØŸÅÿßÿπ ÿßŸÑŸÖÿØŸÜŸäŸë ŸÅŸä ÿ¨ŸÜŸàÿ® ŸÑÿ®ŸÜÿßŸÜ: ...' with post_date 2025-03-15 and post_time 12:14:09
2025-03-15 15:37:34,205 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ÿ£ÿ®Ÿà ŸÅÿßÿπŸàÿ±: ÿπŸÑŸâ ÿßŸÑÿ≠ŸÉŸàŸÖÿ© ÿ•ŸÑÿ∫ÿßÿ° ÿß...' with post_date 2025-03-15 and post_time 12:32:17
2025-03-15 15:37:34,208 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ÿ•ÿ≥ÿ™ŸÖÿ±ÿßÿ± ÿßŸÑÿ≠ŸÖŸÑÿ© ÿßŸÑÿ£ŸÖŸÜŸäÿ© ŸÅŸä ÿ∑ÿ±ÿßÿ®...' with post_date 2025-03-15 and post_time 09:29:52
2025-03-15 15:37:34,212 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ŸÖÿßŸÉÿ±ŸàŸÜ: ÿßÿ™ÿµŸÑÿ™ ÿ®ÿ±ÿ¶Ÿäÿ≥ ÿßŸÑÿ≠ŸÉŸàŸÖÿ© ÿßŸÑ...' with post_date 2025-03-14 and post_time 22:12:01
2025-03-15 15:37:34,215 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ŸÜÿØŸäŸÖ ÿßŸÑÿ¨ŸÖŸäŸÑ ŸÖŸÜ ŸÖÿπÿ±ÿßÿ®: ŸÑŸàÿ¨Ÿàÿ® ÿßŸÑ...' with post_date 2025-03-15 and post_time 08:17:38
2025-03-15 15:37:34,218 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ŸàÿµŸàŸÑ ÿ±ÿ¶Ÿäÿ≥ ÿßŸÑÿ≠ŸÉŸàŸÖÿ© ŸÜŸàÿßŸÅ ÿ≥ŸÑÿßŸÖ ÿ•ŸÑ...' with post_date 2025-03-15 and post_time 11:46:43
2025-03-15 15:37:34,222 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ÿ™ÿ±ÿßŸÖÿ®: ÿ≤ÿπŸäŸÖ ÿ™ŸÜÿ∏ŸäŸÖ ÿßŸÑÿØŸàŸÑÿ© ÿßŸÑÿ•ÿ≥ŸÑ...' with post_date 2025-03-15 and post_time 05:46:03
2025-03-15 15:37:34,224 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ÿπŸÑŸä ŸÖÿ±ÿßÿØ ŸÑŸÑŸÄLBCI: ÿπŸÑŸâ ÿßŸÑÿØŸàŸÑÿ© ÿ£...' with post_date 2025-03-15 and post_time 09:05:50
2025-03-15 15:37:34,229 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ŸÑŸÇÿßÿ°ÿßÿ™ ÿπŸäŸÜ ÿßŸÑÿ™ŸäŸÜÿ©... ÿ®ÿ≠ÿ´ ŸÅŸä ÿ™ÿ∑...' with post_date 2025-03-15 and post_time 13:01:05
2025-03-15 15:37:34,235 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ŸÖÿßŸÉÿ±ŸàŸÜ: ÿßÿ™ÿµŸÑÿ™ ÿ®ÿ±ÿ¶Ÿäÿ≥ ÿßŸÑÿ≠ŸÉŸàŸÖÿ© ÿßŸÑ...' with post_date 2025-03-14 and post_time 22:12:01
2025-03-15 15:37:34,238 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ŸÜÿØŸäŸÖ ÿßŸÑÿ¨ŸÖŸäŸÑ ŸÖŸÜ ŸÖÿπÿ±ÿßÿ®: ŸÑŸàÿ¨Ÿàÿ® ÿßŸÑ...' with post_date 2025-03-15 and post_time 08:17:38
2025-03-15 15:37:34,241 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ÿßŸÑŸÜÿßÿ¥ÿ∑ ÿßŸÑÿ≥Ÿäÿßÿ≥Ÿä ÿØ. ÿπŸÑŸä ŸÖÿ±ÿßÿØ ŸÑŸÑŸÄ...' with post_date 2025-03-15 and post_time 08:52:15
2025-03-15 15:37:34,245 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ŸÑŸÇÿßÿ°ÿßÿ™ ÿπŸäŸÜ ÿßŸÑÿ™ŸäŸÜÿ©... ÿ®ÿ≠ÿ´ ŸÅŸä ÿ™ÿ∑...' with post_date 2025-03-15 and post_time 13:01:05
2025-03-15 15:37:34,248 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ŸàÿµŸàŸÑ ÿ±ÿ¶Ÿäÿ≥ ÿßŸÑÿ≠ŸÉŸàŸÖÿ© ŸÜŸàÿßŸÅ ÿ≥ŸÑÿßŸÖ ÿ•ŸÑ...' with post_date 2025-03-15 and post_time 11:46:43
2025-03-15 15:37:34,251 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ÿßŸÑÿØŸÅÿßÿπ ÿßŸÑŸÖÿØŸÜŸäŸë ŸÅŸä ÿ¨ŸÜŸàÿ® ŸÑÿ®ŸÜÿßŸÜ: ...' with post_date 2025-03-15 and post_time 12:14:09
2025-03-15 15:37:34,253 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ÿ•ÿ¨ÿ™ŸÖÿßÿπ ŸÇÿ±Ÿäÿ® ŸÑŸÄ"ŸÖÿ¨ŸÖŸàÿπÿ© ÿ£ÿµÿØŸÇÿßÿ° ŸÑ...' with post_date 2025-03-15 and post_time 06:15:52
2025-03-15 15:37:34,256 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ÿ¨ŸÜŸàÿ® ÿ•ŸÅÿ±ŸäŸÇŸäÿß ÿ™ÿπÿ™ÿ®ÿ± ÿ∑ÿ±ÿØ ÿ≥ŸÅŸäÿ±Ÿáÿß ...' with post_date 2025-03-15 and post_time 06:30:51
2025-03-15 15:37:34,259 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ÿ™ÿ≥ŸàŸäÿ© ÿ®ÿ±Ÿäÿ∑ÿßŸÜŸäÿ© ŸÑŸÄ"ÿßŸÑŸÜŸÇÿßÿ∑ ÿßŸÑÿÆŸÖÿ≥...' with post_date 2025-03-15 and post_time 05:58:45
2025-03-15 15:37:34,262 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ÿ™ÿ±ÿßŸÖÿ®: ÿ≤ÿπŸäŸÖ ÿ™ŸÜÿ∏ŸäŸÖ ÿßŸÑÿØŸàŸÑÿ© ÿßŸÑÿ•ÿ≥ŸÑ...' with post_date 2025-03-15 and post_time 05:46:03
2025-03-15 15:37:34,264 - src.kafka.consumers.stats - ‚ÑπÔ∏è INFO - stats.py:96 - Top engagement metrics saved to database
2025-03-15 15:37:34,264 - root - ‚ÑπÔ∏è INFO - main.py:53 - Stats consumers finished
2025-03-15 15:37:34,264 - root - ‚ÑπÔ∏è INFO - main.py:87 - Pipeline run completed
