2025-03-15 16:09:44,529 - root - ‚ÑπÔ∏è INFO - main.py:70 - Initializing pipeline
2025-03-15 16:09:44,529 - root - ‚ÑπÔ∏è INFO - main.py:14 - Starting Twitter scraper for @LBCI_NEWS
2025-03-15 16:09:49,473 - root - ‚ÑπÔ∏è INFO - core.py:25 - üöÄ Starting scrape for @LBCI_NEWS
2025-03-15 16:09:53,820 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 5 new tweets (Total: 5)
2025-03-15 16:09:54,499 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 1 new tweets (Total: 6)
2025-03-15 16:09:55,256 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 9)
2025-03-15 16:09:56,009 - root - ‚ÑπÔ∏è INFO - producer.py:22 - Sent batch of 10 tweets (Total: 10)
2025-03-15 16:09:56,009 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 2 new tweets (Total: 11)
2025-03-15 16:09:56,845 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 14)
2025-03-15 16:09:57,687 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 17)
2025-03-15 16:09:58,543 - root - ‚ÑπÔ∏è INFO - producer.py:22 - Sent batch of 10 tweets (Total: 20)
2025-03-15 16:09:58,543 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 20)
2025-03-15 16:09:59,787 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 6 new tweets (Total: 26)
2025-03-15 16:10:00,516 - root - ‚ö†Ô∏è WARNING - core.py:77 - ‚ö†Ô∏è  No new tweets in loaded content
2025-03-15 16:10:00,516 - root - ‚ö†Ô∏è WARNING - core.py:82 - ‚è≥ Retry #1 for 2s
2025-03-15 16:10:03,193 - root - ‚ÑπÔ∏è INFO - producer.py:22 - Sent batch of 10 tweets (Total: 30)
2025-03-15 16:10:03,193 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 4 new tweets (Total: 30)
2025-03-15 16:10:04,120 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 2 new tweets (Total: 32)
2025-03-15 16:10:05,036 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 35)
2025-03-15 16:10:05,842 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 2 new tweets (Total: 37)
2025-03-15 16:10:06,708 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 2 new tweets (Total: 39)
2025-03-15 16:10:07,842 - root - ‚ÑπÔ∏è INFO - producer.py:22 - Sent batch of 10 tweets (Total: 40)
2025-03-15 16:10:07,845 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 5 new tweets (Total: 44)
2025-03-15 16:10:08,619 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 47)
2025-03-15 16:10:09,458 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 2 new tweets (Total: 49)
2025-03-15 16:10:10,307 - root - ‚ÑπÔ∏è INFO - producer.py:22 - Sent batch of 10 tweets (Total: 50)
2025-03-15 16:10:10,307 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 1 new tweets (Total: 50)
2025-03-15 16:10:12,353 - root - ‚ÑπÔ∏è INFO - core.py:93 - ‚úÖ Final count: 50/50 tweets
2025-03-15 16:10:12,353 - root - ‚ÑπÔ∏è INFO - core.py:95 - üéØ Target reached successfully
2025-03-15 16:10:12,354 - root - ‚ÑπÔ∏è INFO - main.py:22 - Scraping completed for @LBCI_NEWS
2025-03-15 16:10:12,354 - root - ‚ÑπÔ∏è INFO - producer.py:29 - Final count: 50 tweets sent
2025-03-15 16:10:12,355 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:216 - Starting Storage Consumer...
2025-03-15 16:10:15,398 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,415 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,416 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,416 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,416 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,416 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,416 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,417 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,417 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,417 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,417 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,418 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,418 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,418 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,418 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,418 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,419 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,419 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,419 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,419 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,419 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,420 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,420 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,420 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,420 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,421 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,421 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,421 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,421 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,421 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,422 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,422 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,422 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,422 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,423 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,423 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,423 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,423 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,423 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,424 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,424 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,424 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,424 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,425 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,425 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,425 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,425 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,425 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,426 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:15,426 - src.kafka.consumers.pipeline - ‚ùå ERROR - pipeline.py:76 - Error processing message: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 60, in process_message
    self.tweet_model.insert_post_and_engagement_metrics(
TypeError: TweetModel.insert_post_and_engagement_metrics() got an unexpected keyword argument 'post_id'
2025-03-15 16:10:45,690 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:220 - Storage Consumer finished.
2025-03-15 16:10:45,690 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:223 - Starting Word Frequency Consumer...
2025-03-15 16:11:18,972 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:128 - Top 20 word frequencies saved to C:\Users\Admin\PycharmProjects\SocialMediaPipeline\data\word_frequencies.json
2025-03-15 16:11:19,033 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:157 - Word frequencies inserted successfully.
2025-03-15 16:11:19,033 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:132 - Word frequencies saved to database
2025-03-15 16:11:19,033 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:229 - Starting Engagement Metrics Consumer...
2025-03-15 16:11:19,033 - src.kafka.consumers.pipeline - ‚ö†Ô∏è WARNING - pipeline.py:149 - No messages in shared store to process
2025-03-15 16:11:19,033 - src.kafka.consumers.pipeline - ‚ö†Ô∏è WARNING - pipeline.py:177 - No engagement data collected to save.
2025-03-15 16:11:19,034 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:235 - Pipeline run completed
2025-03-15 16:11:19,034 - root - ‚ÑπÔ∏è INFO - main.py:92 - Pipeline run completed
