2025-03-15 15:57:38,190 - root - ‚ÑπÔ∏è INFO - main.py:70 - Initializing pipeline
2025-03-15 15:57:38,191 - root - ‚ÑπÔ∏è INFO - main.py:14 - Starting Twitter scraper for @LBCI_NEWS
2025-03-15 15:57:44,281 - root - ‚ÑπÔ∏è INFO - core.py:25 - üöÄ Starting scrape for @LBCI_NEWS
2025-03-15 15:57:48,826 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 5 new tweets (Total: 5)
2025-03-15 15:57:49,535 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 1 new tweets (Total: 6)
2025-03-15 15:57:50,321 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 9)
2025-03-15 15:57:51,027 - root - ‚ÑπÔ∏è INFO - producer.py:22 - Sent batch of 10 tweets (Total: 10)
2025-03-15 15:57:51,028 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 2 new tweets (Total: 11)
2025-03-15 15:57:51,799 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 14)
2025-03-15 15:57:52,644 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 17)
2025-03-15 15:57:53,486 - root - ‚ÑπÔ∏è INFO - producer.py:22 - Sent batch of 10 tweets (Total: 20)
2025-03-15 15:57:53,486 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 20)
2025-03-15 15:57:55,013 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 7 new tweets (Total: 27)
2025-03-15 15:57:55,708 - root - ‚ö†Ô∏è WARNING - core.py:77 - ‚ö†Ô∏è  No new tweets in loaded content
2025-03-15 15:57:55,708 - root - ‚ö†Ô∏è WARNING - core.py:82 - ‚è≥ Retry #1 for 2s
2025-03-15 15:57:58,459 - root - ‚ÑπÔ∏è INFO - producer.py:22 - Sent batch of 10 tweets (Total: 30)
2025-03-15 15:57:58,460 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 30)
2025-03-15 15:57:59,414 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 2 new tweets (Total: 32)
2025-03-15 15:58:00,314 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 35)
2025-03-15 15:58:01,140 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 2 new tweets (Total: 37)
2025-03-15 15:58:02,051 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 2 new tweets (Total: 39)
2025-03-15 15:58:03,157 - root - ‚ÑπÔ∏è INFO - producer.py:22 - Sent batch of 10 tweets (Total: 40)
2025-03-15 15:58:03,160 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 5 new tweets (Total: 44)
2025-03-15 15:58:03,921 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 3 new tweets (Total: 47)
2025-03-15 15:58:04,732 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 2 new tweets (Total: 49)
2025-03-15 15:58:05,574 - root - ‚ÑπÔ∏è INFO - producer.py:22 - Sent batch of 10 tweets (Total: 50)
2025-03-15 15:58:05,574 - root - ‚ÑπÔ∏è INFO - core.py:75 - üì¶ Collected 1 new tweets (Total: 50)
2025-03-15 15:58:07,618 - root - ‚ÑπÔ∏è INFO - core.py:93 - ‚úÖ Final count: 50/50 tweets
2025-03-15 15:58:07,618 - root - ‚ÑπÔ∏è INFO - core.py:95 - üéØ Target reached successfully
2025-03-15 15:58:07,618 - root - ‚ÑπÔ∏è INFO - main.py:22 - Scraping completed for @LBCI_NEWS
2025-03-15 15:58:07,619 - root - ‚ÑπÔ∏è INFO - producer.py:29 - Final count: 50 tweets sent
2025-03-15 15:58:07,620 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:84 - Starting coordinated pipeline
2025-03-15 15:58:07,620 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:87 - Starting Coordinated Storage Consumer...
2025-03-15 15:58:10,683 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,685 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,688 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,689 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,691 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,693 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,694 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,696 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,697 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,700 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,701 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,702 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,704 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,705 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,707 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,709 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,712 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,713 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,714 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,715 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,719 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,720 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,722 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,723 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,726 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,728 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,729 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,731 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,733 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,735 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,737 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,738 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,741 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,742 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,744 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,746 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,749 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,750 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,752 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,755 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,757 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,760 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,762 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,765 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,766 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,769 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,771 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,772 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,774 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,776 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,778 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,781 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,783 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,784 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,787 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,789 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,791 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,793 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,796 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,797 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,799 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,801 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,803 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,805 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,807 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,808 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,811 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,813 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,815 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,817 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,819 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,821 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,823 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,825 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,827 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,829 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,832 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,833 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,836 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,837 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,839 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,841 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,843 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,845 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,848 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,849 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,851 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,853 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,855 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,857 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,859 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,861 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,863 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,865 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,867 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,869 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,871 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,873 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:10,875 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:42 - Platforms already exist.
2025-03-15 15:58:10,876 - src.kafka.consumers.storage - ‚ùå ERROR - storage.py:51 - Error processing message: Commands out of sync; you can't run this command now
2025-03-15 15:58:41,141 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:91 - Storage Consumer finished.
2025-03-15 15:58:41,141 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:95 - Collected 50 messages for analysis
2025-03-15 15:58:41,141 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:98 - Starting Coordinated Word Frequency Consumer...
2025-03-15 15:58:41,142 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,144 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,145 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,145 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,146 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,150 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,150 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,151 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,151 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,151 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,151 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,152 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,153 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,153 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,153 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,154 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,154 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,154 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,155 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,156 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,156 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,156 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,157 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,157 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,157 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,158 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,158 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,159 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,159 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,159 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,160 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,160 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,160 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,161 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,161 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,161 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,162 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,162 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,163 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,163 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,164 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,164 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,164 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,165 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,165 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,166 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,166 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,166 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,167 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,167 - src.kafka.consumers.stats - ‚ùå ERROR - pipeline.py:66 - Error processing shared message: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\pipeline.py", line 64, in process_shared_messages
    self.process_tweet(message)
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\kafka\consumers\stats.py", line 32, in process_tweet
    keywords = extract_keywords(tweet['content'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\SocialMediaPipeline\src\utils\data_helpers.py", line 104, in extract_keywords
    if word not in stop_words and len(word) >= min_length]
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2025-03-15 15:58:41,167 - src.kafka.consumers.stats - ‚ÑπÔ∏è INFO - stats.py:48 - Top 20 word frequencies saved to C:\Users\Admin\PycharmProjects\SocialMediaPipeline\data\word_frequencies.json
2025-03-15 15:58:41,168 - src.models.relational.tweets - ‚ÑπÔ∏è INFO - tweets.py:157 - Word frequencies inserted successfully.
2025-03-15 15:58:41,168 - src.kafka.consumers.stats - ‚ÑπÔ∏è INFO - stats.py:52 - Word frequencies saved to database
2025-03-15 15:58:41,168 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:102 - Word Frequency Consumer finished.
2025-03-15 15:58:41,168 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:105 - Starting Coordinated Engagement Consumer...
2025-03-15 15:58:41,179 - src.kafka.consumers.stats - ‚ÑπÔ∏è INFO - stats.py:90 - Engagement metrics saved to C:\Users\Admin\PycharmProjects\SocialMediaPipeline\data\tweets_engagement.json
2025-03-15 15:58:41,183 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ÿßÿ≥ÿ™ŸáÿØÿßŸÅ ÿ≥Ÿäÿßÿ±ÿ© ŸÅŸä ÿ®ÿ±ÿ¨ ÿßŸÑŸÖŸÑŸàŸÉ...' with post_date 2025-03-15 and post_time 11:43:27
2025-03-15 15:58:41,186 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ÿßŸÑÿØŸÅÿßÿπ ÿßŸÑŸÖÿØŸÜŸäŸë ŸÅŸä ÿ¨ŸÜŸàÿ® ŸÑÿ®ŸÜÿßŸÜ: ...' with post_date 2025-03-15 and post_time 12:14:09
2025-03-15 15:58:41,187 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ÿ£ÿ®Ÿà ŸÅÿßÿπŸàÿ±: ÿπŸÑŸâ ÿßŸÑÿ≠ŸÉŸàŸÖÿ© ÿ•ŸÑÿ∫ÿßÿ° ÿß...' with post_date 2025-03-15 and post_time 12:32:17
2025-03-15 15:58:41,189 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ÿ•ÿ≥ÿ™ŸÖÿ±ÿßÿ± ÿßŸÑÿ≠ŸÖŸÑÿ© ÿßŸÑÿ£ŸÖŸÜŸäÿ© ŸÅŸä ÿ∑ÿ±ÿßÿ®...' with post_date 2025-03-15 and post_time 09:29:52
2025-03-15 15:58:41,191 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ŸàÿµŸàŸÑ ÿ±ÿ¶Ÿäÿ≥ ÿßŸÑÿ≠ŸÉŸàŸÖÿ© ŸÜŸàÿßŸÅ ÿ≥ŸÑÿßŸÖ ÿ•ŸÑ...' with post_date 2025-03-15 and post_time 11:46:43
2025-03-15 15:58:41,192 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ŸÜÿØŸäŸÖ ÿßŸÑÿ¨ŸÖŸäŸÑ ŸÖŸÜ ŸÖÿπÿ±ÿßÿ®: ŸÑŸàÿ¨Ÿàÿ® ÿßŸÑ...' with post_date 2025-03-15 and post_time 08:17:38
2025-03-15 15:58:41,193 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like '"ÿ≠ŸÖÿßÿ≥": ŸÜÿ∑ÿßŸÑÿ® ÿßŸÑŸàÿ≥ÿ∑ÿßÿ° ÿ®ÿßŸÑÿ™ÿ≠ÿ±ŸÉ ...' with post_date 2025-03-15 and post_time 13:32:42
2025-03-15 15:58:41,195 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ÿ™ÿ±ÿßŸÖÿ®: ÿ≤ÿπŸäŸÖ ÿ™ŸÜÿ∏ŸäŸÖ ÿßŸÑÿØŸàŸÑÿ© ÿßŸÑÿ•ÿ≥ŸÑ...' with post_date 2025-03-15 and post_time 05:46:03
2025-03-15 15:58:41,197 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ÿπŸÑŸä ŸÖÿ±ÿßÿØ ŸÑŸÑŸÄLBCI: ÿπŸÑŸâ ÿßŸÑÿØŸàŸÑÿ© ÿ£...' with post_date 2025-03-15 and post_time 09:05:50
2025-03-15 15:58:41,199 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:208 - Error: Post not found for like 'ŸÑŸÇÿßÿ°ÿßÿ™ ÿπŸäŸÜ ÿßŸÑÿ™ŸäŸÜÿ©... ÿ®ÿ≠ÿ´ ŸÅŸä ÿ™ÿ∑...' with post_date 2025-03-15 and post_time 13:01:05
2025-03-15 15:58:41,202 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ŸÜÿØŸäŸÖ ÿßŸÑÿ¨ŸÖŸäŸÑ ŸÖŸÜ ŸÖÿπÿ±ÿßÿ®: ŸÑŸàÿ¨Ÿàÿ® ÿßŸÑ...' with post_date 2025-03-15 and post_time 08:17:38
2025-03-15 15:58:41,203 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ÿßŸÑŸÜÿßÿ¥ÿ∑ ÿßŸÑÿ≥Ÿäÿßÿ≥Ÿä ÿØ. ÿπŸÑŸä ŸÖÿ±ÿßÿØ ŸÑŸÑŸÄ...' with post_date 2025-03-15 and post_time 08:52:15
2025-03-15 15:58:41,205 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ŸÑŸÇÿßÿ°ÿßÿ™ ÿπŸäŸÜ ÿßŸÑÿ™ŸäŸÜÿ©... ÿ®ÿ≠ÿ´ ŸÅŸä ÿ™ÿ∑...' with post_date 2025-03-15 and post_time 13:01:05
2025-03-15 15:58:41,206 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ŸàÿµŸàŸÑ ÿ±ÿ¶Ÿäÿ≥ ÿßŸÑÿ≠ŸÉŸàŸÖÿ© ŸÜŸàÿßŸÅ ÿ≥ŸÑÿßŸÖ ÿ•ŸÑ...' with post_date 2025-03-15 and post_time 11:46:43
2025-03-15 15:58:41,207 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ÿßŸÑÿØŸÅÿßÿπ ÿßŸÑŸÖÿØŸÜŸäŸë ŸÅŸä ÿ¨ŸÜŸàÿ® ŸÑÿ®ŸÜÿßŸÜ: ...' with post_date 2025-03-15 and post_time 12:14:09
2025-03-15 15:58:41,209 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ÿ•ÿ¨ÿ™ŸÖÿßÿπ ŸÇÿ±Ÿäÿ® ŸÑŸÄ"ŸÖÿ¨ŸÖŸàÿπÿ© ÿ£ÿµÿØŸÇÿßÿ° ŸÑ...' with post_date 2025-03-15 and post_time 06:15:52
2025-03-15 15:58:41,211 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ÿ¨ŸÜŸàÿ® ÿ•ŸÅÿ±ŸäŸÇŸäÿß ÿ™ÿπÿ™ÿ®ÿ± ÿ∑ÿ±ÿØ ÿ≥ŸÅŸäÿ±Ÿáÿß ...' with post_date 2025-03-15 and post_time 06:30:51
2025-03-15 15:58:41,212 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ÿ™ÿ≥ŸàŸäÿ© ÿ®ÿ±Ÿäÿ∑ÿßŸÜŸäÿ© ŸÑŸÄ"ÿßŸÑŸÜŸÇÿßÿ∑ ÿßŸÑÿÆŸÖÿ≥...' with post_date 2025-03-15 and post_time 05:58:45
2025-03-15 15:58:41,213 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ÿ™ÿ±ÿßŸÖÿ®: ÿ≤ÿπŸäŸÖ ÿ™ŸÜÿ∏ŸäŸÖ ÿßŸÑÿØŸàŸÑÿ© ÿßŸÑÿ•ÿ≥ŸÑ...' with post_date 2025-03-15 and post_time 05:46:03
2025-03-15 15:58:41,215 - src.models.relational.tweets - ‚ö†Ô∏è WARNING - tweets.py:182 - Error: Post not found for comment 'ÿ£ÿ®Ÿà ŸÅÿßÿπŸàÿ±: ÿπŸÑŸâ ÿßŸÑÿ≠ŸÉŸàŸÖÿ© ÿ•ŸÑÿ∫ÿßÿ° ÿß...' with post_date 2025-03-15 and post_time 12:32:17
2025-03-15 15:58:41,215 - src.kafka.consumers.stats - ‚ÑπÔ∏è INFO - stats.py:96 - Top engagement metrics saved to database
2025-03-15 15:58:41,216 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:109 - Engagement Consumer finished.
2025-03-15 15:58:41,216 - src.kafka.consumers.pipeline - ‚ÑπÔ∏è INFO - pipeline.py:111 - Coordinated pipeline run completed
2025-03-15 15:58:41,217 - root - ‚ÑπÔ∏è INFO - main.py:92 - Pipeline run completed
